### ISSUE TITLE
Сделать скриншоты для документации

### ISSUE THREAD

**Issue by galievruslan** [galievruslan/mss-mobile#51]
Сделать скриншоты приложения для документации

**Comment by golfarid** [comment]
![scr00](https://f.cloud.github.com/assets/2780407/595248/f0a1f722-caef-11e2-91f8-c1e8a33ee7ad.jpg)
![scr04](https://f.cloud.github.com/assets/2780407/595249/f0bfdbe8-caef-11e2-9b56-bfab05239dab.jpg)
![scr05](https://f.cloud.github.com/assets/2780407/595250/f0ddbb4a-caef-11e2-99f3-95341eb42d8d.jpg)
![scr01](https://f.cloud.github.com/assets/2780407/595251/f0e9f748-caef-11e2-82e6-af323c7cc542.jpg)
![scr02](https://f.cloud.github.com/assets/2780407/595252/f0e88606-caef-11e2-9b03-73c0eda49ea0.jpg)
![scr03](https://f.cloud.github.com/assets/2780407/595253/f0eeddda-caef-11e2-9494-8d723db00591.jpg)
![scr08](https://f.cloud.github.com/assets/2780407/595254/f0fb6956-caef-11e2-8d29-320fbd34907f.jpg)
![scr10](https://f.cloud.github.com/assets/2780407/595255/f1048a54-caef-11e2-8775-d858dd0c492a.jpg)
![scr09](https://f.cloud.github.com/assets/2780407/595256/f108a724-caef-11e2-9d57-00c201751241.jpg)
![scr11](https://f.cloud.github.com/assets/2780407/595257/f10d425c-caef-11e2-9f7a-c28a9bb9f31e.jpg)
![scr06](https://f.cloud.github.com/assets/2780407/595258/f11232a8-caef-11e2-9792-96237f8409d5.jpg)
![scr07](https://f.cloud.github.com/assets/2780407/595259/f112f3e6-caef-11e2-90c7-09656a1a4d26.jpg)
![scr12](https://f.cloud.github.com/assets/2780407/595260/f1187f1e-caef-11e2-8a0c-8c7de6c50dab.jpg)
![scr13](https://f.cloud.github.com/assets/2780407/595261/f1200fcc-caef-11e2-9f16-64711340edea.jpg)
![scr14](https://f.cloud.github.com/assets/2780407/595262/f1257188-caef-11e2-83d6-9fbb076701b6.jpg)
![scr15](https://f.cloud.github.com/assets/2780407/595263/f12a7200-caef-11e2-9626-05b88a8457d6.jpg)
![scr16](https://f.cloud.github.com/assets/2780407/595264/f131744c-caef-11e2-9503-f8dd18f7b658.jpg)
![scr17](https://f.cloud.github.com/assets/2780407/595265/f1319fa8-caef-11e2-9e6e-442de6238ca2.jpg)
![scr18](https://f.cloud.github.com/assets/2780407/595266/f1357c68-caef-11e2-83e5-1b404fe44694.jpg)
![scr19](https://f.cloud.github.com/assets/2780407/595267/f13d13e2-caef-11e2-8a9e-f553a31bfb37.jpg)
