### ISSUE TITLE
Недостающие скриншоты

### ISSUE THREAD

**Issue by galievruslan** [galievruslan/mss-mobile#54]
Сделать следующие скриншоты:
1. Окна синхронизации, чтобы была дата последней синхронизации.
2. Вкладки синхронизация окна настроек

**Comment by golfarid** [comment]
![scr00](https://f.cloud.github.com/assets/2780407/601989/20888406-cc8f-11e2-992e-9b7e7f98b76e.jpg)
![scr03](https://f.cloud.github.com/assets/2780407/601990/20d4359a-cc8f-11e2-8b4e-7ca91960250a.jpg)
![scr01](https://f.cloud.github.com/assets/2780407/601991/20d6e4f2-cc8f-11e2-80c7-b22f00d88f15.jpg)
![scr04](https://f.cloud.github.com/assets/2780407/601993/20db4ede-cc8f-11e2-8847-c0c071fccbe2.jpg)
![scr02](https://f.cloud.github.com/assets/2780407/601992/20d8436a-cc8f-11e2-9dd8-389481d5b5b9.jpg)
